// kul-app-react/src/App.tsx
import { useReducer } from "react";

export type Appstate = {
  name: string;
  erKul: boolean;
};

export const initialState: Appstate = {
  name: "Hello",
  erKul: true,
};

export type AppAction =
  | {
      type: "SETT_NAVN";
      payload: string;
    }
  | {
      type: "TOGGLE_KUL";
    };

export function reducer(state: Appstate, action: AppAction): Appstate {
  switch (action.type) {
    case "SETT_NAVN":
      const nyErkul =
        "øyvind" === action.payload.toLowerCase() ? true : state.erKul;
      return {
        ...state,
        name: action.payload,
        erKul: nyErkul,
      };
    case "TOGGLE_KUL":
      return {
        ...state,
        erKul: !state.erKul,
      };
  }
}

function App() {
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <>
      <h1>
        {state.name} er {state.erKul ? "" : "IKKE"} kul!
      </h1>

      <label>
        Navn:{" "}
        <input
          value={state.name}
          onChange={(event) =>
            dispatch({ type: "SETT_NAVN", payload: event.target.value })
          }
        />
      </label>
      <label>
        Er kul?
        <input
          type="checkbox"
          checked={state.erKul}
          onChange={() => dispatch({ type: "TOGGLE_KUL" })}
          disabled={state.name.toLowerCase() === "øyvind"}
        />
      </label>
    </>
  );
}

export default App;

// kul-app-svelte/src/App.svelte
<script lang="ts">
  import { writable } from "svelte/store";

  type Appstate = {
    name: string;
    erKul: boolean;
  };

  const initialState: Appstate = {
    name: "Hello",
    erKul: true,
  };

  function useAppstate(initialState: Appstate) {
    const { subscribe, update } = writable(initialState);
    return {
      subscribe,
      settNavn: (name: string) =>
        update((state) => {
          const nyErKul = "øyvind" === name.toLowerCase() ? true : state.erKul;
          return { name, erKul: nyErKul };
        }),
      toggleKul: () => update((state) => ({ ...state, erKul: !state.erKul })),
    };
  }

  let appState = useAppstate(initialState);
</script>

<h1>
  {$appState.name} er {$appState.erKul ? "" : "IKKE"} kul!
</h1>

<label>
  Navn:{" "}
  <input
    value={$appState.name}
    on:input={(event) => appState.settNavn(event.target["value"])}
  />
</label>
<label>
  Er kul?
  <input
    type="checkbox"
    checked={$appState.erKul}
    on:change={() => appState.toggleKul()}
    disabled={$appState.name.toLowerCase() === "øyvind"}
  />
</label>
